version: "3.9"
services:
  mongo:
    image: mongo:4.0.4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb:/files/new_data/db

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.data.mongodb.database" : "cryptocurrency-price",
            "cryptocurrency.name" : "BTC,ETH,XRP",
            "spring.data.mongodb.host" : "mongo",
            "spring.data.mongodb.port" : "27017",
            "cryptocurrency.thread-sleep-time" : "5000"
          }'
