spring:
  data:
    mongodb:
      database: cryptocurrency-price
      host: localhost
      port: 27017
cryptocurrency:
  name: BTC,ETH,XRP
  sleepTime: 5000

nats:
  connection:
    url: nats://localhost:4222
